### ISSUE TITLE
Allow specification for custom Docker image in `release` step

### ISSUE THREAD

**Issue by rfranzke** [gardener/cc-utils#227]
In a release process we have to generate code (via Go means). However, the release step uses `alpine`. Consequently, we have to download (and compile!) Go ourselves in our `prepare_release` hook in order to later allow code generation.
That's very cumbersome. Can you please allow us to specify another base image (not `alpine`) for our release step so that we don't need to install Go ourselves?!

/cc @adracus

**Comment by ccwienk** [comment]
@rfranzke : is this still valid with https://github.com/gardener/cc-utils/pull/228 being in?

As for the actually requested feature, this will (unfortunately) not be that easy. We could of course make the image in which the release step is executed configurable. However, we require a recent version of `cc-utils` + runtime dependencies, because we need to run our deployment gear from there.

There is already a go image which meets those requirements (`eu.gcr.io/gardener-project/cc/job-image-golang`). However, this is not maintained regularly. So using it would come at the price of potentially breaking release builds, as we may introduce incompatible changes over time and do not maintain said image.

**Comment by rfranzke** [comment]
@adracus ?

**Comment by adracus** [comment]
#228 allowed us for some convenience, but still this feature is still valid nevertheless - atm we need to maintain a golang installation in our own scripts. Using a docker image for any callback would ease the situation by a whole lot.
This is why I'd not only say this applies for the release step, but rather for any callback the pipeline wants to trigger.

**Comment by vpnachev** [comment]
Any update here?
I am very frustrated to understand that we are installing golang from the internet on the fly instead of using image configured in the Dockerfile, or at least at the pipeline definition.

**Comment by ccwienk** [comment]
dear @rfranzke , @ialidzhikov @vpnachev 

after recently discovering there in fact _is_ a viable option to run containers within concourse task steps, I implemented the option to run release-callbacks in (oci) containers with custom container images.

The contract towards the script remains unchanged. The same environment variables are passed in (note that the main repository will be mounted at `/mnt/main_repo`, though (this should not require changes in the callback script, provided it relies on the `MAIN_REPO` env var, only).

The new configuration option ~~is~~ will be documented [here](https://gardener.github.io/cc-utils/traits/release.html#trait-release). Need to fix some unrelated issue w/ our documentation build..

In case you would like to try it out, this is the new configuration you could add to your `release` trait(s):

```
traits:
  release:
    release_callback_image_reference:
      image_reference: 'eu.gcr.io/your-image/here:1.2.3'
```

Note that I still need to add image-pull authentication, so only public images will work for now. Also, there is currently no caching in place. I believe at least the latter should be acceptable for releases, as those do not happen that frequently.

**Comment by ccwienk** [comment]
I also added authentication by now (injected automatically)

**Comment by ccwienk** [comment]
Since I think the request has been resolved, I close the ticket. Please do follow-up/reopen in case you see this differently, or stumble upon issues w/ the proposed solution.
